Repository SSSD/sssd-test-framework, pull requests merged in 2023-09, with the labels that each got.

#44 Remove references to obsolete 'config_file_version' sssd.conf option
  docs/guides/using-roles.rst
  sssd_test_framework/utils/sssd.py
Labels: Waiting for review

#28 Add a module for nsldc support.
  sssd_test_framework/utils/sssd.py
Labels: enhancement

#43 doc: added importance and custom markers section
  docs/marks.rst
Labels: Changes requested
