Repository SSSD/sssd-test-framework, pull requests merged in 2023-11, with the labels that each got.

#58 Tools: wait_for() added
  sssd_test_framework/utils/tools.py
Labels: Waiting for review

#51 Roles: import utility to perform traffic control
  sssd_test_framework/roles/base.py
Labels: Blocked

#31 pam: adding support to manage pam modules; pam_access and pam_faillock
  docs/guides/index.rst
  docs/guides/pam.rst
  sssd_test_framework/roles/base.py
  sssd_test_framework/utils/pam.py
  sssd_test_framework/utils/sssd.py
  sssd_test_framework/utils/tools.py
Labels: enhancement, Changes requested
