Repository SSSD/sssd-test-framework, pull requests merged in 2024-02, with the labels that each got.

#82 authentication.py: fixing docstring type parameters
  sssd_test_framework/utils/authentication.py
Labels: documentation

#86 utils: adding gssapi common configuration
  sssd_test_framework/utils/sssd.py
Labels: enhancement, Waiting for review

#85 utils: adding output capture for su password authentication
  sssd_test_framework/utils/authentication.py
Labels: enhancement, Waiting for review

#87 CLIENT: fix "non-privileged" feature detection
  sssd_test_framework/hosts/client.py
Labels: Waiting for review
