Repository SSSD/sssd-test-framework, pull requests merged in 2025-04, with the labels that each got.

#162 configuring sssd to use local domain when sssd.common.local() is called
  sssd_test_framework/utils/sssd.py
Labels: Trivial, Accepted

#170 roles.ldap: moved the creation of an aci to the role setup method, making it a default configuration for all tests.
  sssd_test_framework/roles/ldap.py
Labels: Waiting for review, Trivial

#173 authentication.py, adding string returned by centos 9 to expect methods
  sssd_test_framework/utils/authentication.py
Labels: Trivial, Accepted

#174 ipa: improvements to IPA artifacts
  sssd_test_framework/hosts/ipa.py
Labels: Trivial

#168 topologies: adding any directory server (ds)
  sssd_test_framework/topology.py
Labels: Waiting for review, Trivial

#175 Uniform admin user declaration
  sssd_test_framework/hosts/ad.py
  sssd_test_framework/hosts/ipa.py
  sssd_test_framework/hosts/samba.py
  sssd_test_framework/roles/samba.py
Labels: Waiting for review
